const state={token:"",overview:null,runs:[],tasks:[],knowledge:[],actions:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=v=>v?new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"—";
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function setView(name){$$('.nav-item').forEach(x=>x.classList.toggle('is-active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.toggle('is-visible',x.id===`view-${name}`));const titles={overview:"今天的梦境脉络",runs:"梦境时间线",tasks:"任务树账本",knowledge:"知识生命周期",decisions:"人工决策门"};$('#page-title').textContent=titles[name];location.hash=name}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
function renderOverview(){const o=state.overview;$('#reviewed-count').textContent=o.reviewed_sessions.toLocaleString();const ratio=o.ledger_sessions?Math.round(o.reviewed_sessions/o.ledger_sessions*100):0;$('#review-meter').style.width=`${ratio}%`;$('#review-caption').textContent=`共 ${o.ledger_sessions.toLocaleString()} 条记录 · ${ratio}% 已形成语义检查点`;$('#signal-list').innerHTML=[[o.pending_candidates,"待决策候选"],[o.active_validations,"活跃验证"],[o.review_cards,"任务树"],[o.knowledge_items,"知识项"]].map(([n,l])=>`<div class="signal"><strong>${n}</strong><span>${l}</span></div>`).join('');renderRuns(o.recent_runs,$('#recent-runs'),true);const labels={observed:"观察",emerging:"形成中",established:"已建立",retired:"已退休"};const total=Object.values(o.maturity).reduce((a,b)=>a+b,0)||1;$('#maturity-track').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="maturity-segment ${k}" style="flex:${o.maturity[k]||.18}"><b>${o.maturity[k]||0}</b><span>${l}</span></div>`).join('')}
function renderRuns(runs,target,compact=false){if(!runs.length){target.innerHTML='<div class="empty-state">还没有记录完整的梦境周期。</div>';return}if(compact){target.innerHTML=runs.map(r=>`<article class="run-card"><time>${fmt(r.started_at)}</time><h3>${esc(r.title)}</h3><p>${r.origin==='imported_report'?'由历史报告恢复':'结构化梦境周期'} · ${esc(r.status)}</p></article>`).join('');return}target.innerHTML=runs.map(r=>`<article class="timeline-entry"><time>${fmt(r.started_at)}</time><div><h3>${esc(r.title)}</h3><p>${r.report_path?`报告 · ${esc(r.report_path)}`:'这一轮尚未生成周期报告'}</p></div><span class="run-status">${esc(r.status)}</span></article>`).join('')}
function renderTasks(){const q=$('#task-search').value.toLowerCase();const status=$('#task-status').value;const tasks=state.tasks.filter(t=>(!status||t.status===status)&&(!q||`${t.title} ${t.task_ref}`.toLowerCase().includes(q)));$('#task-rows').innerHTML=tasks.map(t=>`<tr><td><small>${esc(t.task_ref)}</small><br>${esc(t.title)}</td><td>${esc(t.project||'—')}</td><td><span class="status-dot ${esc(t.status)}">${esc(t.status)}</span></td><td>${t.rollout_count} / ${t.subagent_count} 子代理</td><td>${fmt(t.last_updated_at)}</td></tr>`).join('')||'<tr><td colspan="5">没有符合条件的任务。</td></tr>'}
$('#task-search').addEventListener('input',renderTasks);$('#task-status').addEventListener('change',renderTasks);
function renderKnowledge(){const index=$('#knowledge-index');index.innerHTML=state.knowledge.map((k,i)=>`<button class="knowledge-link ${i===0?'is-active':''}" data-kd="${esc(k.knowledge_id)}"><small>${esc(k.knowledge_id)} · ${esc(k.maturity)}</small><b>${esc(k.title)}</b></button>`).join('');$$('.knowledge-link').forEach(b=>b.addEventListener('click',()=>{ $$('.knowledge-link').forEach(x=>x.classList.toggle('is-active',x===b));showKnowledge(b.dataset.kd)}));if(state.knowledge[0])showKnowledge(state.knowledge[0].knowledge_id)}
function showKnowledge(id){const k=state.knowledge.find(x=>x.knowledge_id===id);if(!k)return;const groups=[["观察",k.observations,"observation_id"],["候选",k.candidates,"candidate_id"],["决定",k.decisions,"decision_id"],["采用",k.adoptions,"adoption_id"],["验证",k.validations,"validation_id"]];$('#knowledge-detail').innerHTML=`<p class="kicker">${esc(k.knowledge_id)} · ${esc(k.kind)}</p><h2>${esc(k.title)}</h2><p class="summary">${esc(k.summary)}</p><dl><div class="lifecycle-row"><dt>成熟度</dt><dd><span class="tag">${esc(k.maturity)}</span><span class="tag">${esc(k.scope)}</span></dd></div>${groups.map(([l,x,key])=>`<div class="lifecycle-row"><dt>${l} · ${x.length}</dt><dd>${x.length?x.map(v=>`<span class="tag">${esc(v[key])} ${esc(v.status||v.polarity||'')}</span>`).join(''):'暂无'}</dd></div>`).join('')}<div class="lifecycle-row"><dt>下一动作</dt><dd>${esc(k.next_action||'待确定')}</dd></div></dl>`}
function candidates(){return state.knowledge.flatMap(k=>k.candidates.filter(c=>c.status==='proposed').map(c=>({...c,knowledge_id:k.knowledge_id,knowledge_title:k.title})))}
function renderDecisions(){const list=candidates();$('#decision-list').innerHTML=list.map(c=>`<article class="decision-card"><div class="decision-id">${esc(c.candidate_id)}<br>${esc(c.confidence)}</div><div><h3>${esc(c.title)}</h3><p>${esc(c.recommended_action||c.interpretation||c.observation)}</p></div><div class="decision-buttons"><button data-decision="accepted" data-kd="${c.knowledge_id}" data-can="${c.candidate_id}" data-title="${esc(c.title)}">接受</button><button data-decision="rejected" data-kd="${c.knowledge_id}" data-can="${c.candidate_id}" data-title="${esc(c.title)}">拒绝</button><button data-decision="continue_observing" data-kd="${c.knowledge_id}" data-can="${c.candidate_id}" data-title="${esc(c.title)}">继续观察</button></div></article>`).join('')||'<div class="empty-state">当前没有等待判断的候选。</div>';$$('[data-decision]').forEach(b=>b.addEventListener('click',()=>openDecision(b)));$('#action-log').innerHTML=state.actions.map(a=>`<div class="action-row"><code>${esc(a.action_id)}</code><span>${esc(a.action_type)}</span><span>${esc(a.reason)}</span><b>${esc(a.status)}</b></div>`).join('')||'<p class="empty-state">还没有页面操作。</p>'}
function openDecision(b){$('#dialog-knowledge-id').value=b.dataset.kd;$('#dialog-candidate-id').value=b.dataset.can;$('#dialog-action').value=b.dataset.decision;$('#dialog-title').textContent=b.dataset.title;$('#dialog-copy').textContent={accepted:"接受后，候选才能进入采用与验证。",rejected:"拒绝会保留证据与原因，不会删除候选。",continue_observing:"保持 proposed 状态，并记录继续观察的理由。"}[b.dataset.decision];$('#decision-reason').value='';$('#form-status').textContent='';$('#decision-dialog').showModal();setTimeout(()=>$('#decision-reason').focus(),50)}
$$('[data-dialog-close]').forEach(b=>b.addEventListener('click',()=>$('#decision-dialog').close()));
$('#decision-form').addEventListener('submit',async e=>{e.preventDefault();const reason=$('#decision-reason').value.trim();if(reason.length<3){$('#form-status').textContent='请留下至少 3 个字的判断依据。';return}$('#decision-submit').disabled=true;$('#form-status').textContent='正在写入可追溯记录…';try{await api('/api/candidate-actions',{method:'POST',headers:{'X-Dream-Token':state.token},body:JSON.stringify({action:$('#dialog-action').value,knowledge_id:$('#dialog-knowledge-id').value,candidate_id:$('#dialog-candidate-id').value,reason})});await loadData();$('#decision-dialog').close()}catch(err){$('#form-status').textContent=err.message}finally{$('#decision-submit').disabled=false}});
async function loadData(){const [overview,runs,tasks,knowledge,actions]=await Promise.all([api('/api/overview'),api('/api/runs'),api('/api/tasks'),api('/api/knowledge'),api('/api/actions')]);state.overview=overview;state.runs=runs.runs;state.tasks=tasks.tasks;state.knowledge=knowledge.items;state.actions=actions.actions;renderOverview();renderRuns(state.runs,$('#runs-list'));renderTasks();renderKnowledge();renderDecisions()}
async function boot(){try{const config=await api('/api/config');state.token=config.token;$('#workspace-name').textContent=config.workspace;await loadData();setView((location.hash||'#overview').slice(1))}catch(err){document.body.innerHTML=`<main class="empty-state">Dream Console 无法读取本地 Workspace：${esc(err.message)}</main>`}}boot();
